language: go

go:
  - 1.12.x
  - tip

os:
  - linux

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

branches:
  only:
    - master

script:
  - go get -v github.com/Masterminds/glide
  - make build style codecov
