language: go

go:
  - 1.14.x
  - tip

os:
  - linux

services:
  - docker

branches:
  only:
    - main
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

addons:
  sonarcloud:
    organization: "xmidt-org"
    token:
      secure: "gSf6lMqWOVhAb7lvrzVmjAPlwAd2neDve5qlL76I5jXdHEJjKIMKsJ3SuyjA0X/fCRm8tc6AdoQoOsdhxVLOvpeA6rvioo+tfnTF82MCv8RpRfxdrym0NcqR+N0oN53MTeG2zUsKvrIi6Uh7dPwF8FW3Fv5EGPaMAi0qb8bwkC5XZu1VfpDyxAU+8fpsRWlpAS2nYM9TSoWHdNJpWt5pnoJsRTIA1/yILEI24IzI58zYqUpS3lxmRUNcXic+K5IE4X75o81AB1BmDYfy44Y5VAEyhR5EtIFo4EDgfwm86Qy1alX9NWZbI+X5N2QinArTCXF+EPBf/ifKJgyl4kQ2K0CtR0YcvUO1Uf4svT0IASBsiSjZS0voJ9ZJspjozDzG8cDjsurcwGYtOW6NfPQ524aMVlKgiEU1bbXldiaYt6JQ+J73lBBqCBaQCE2l8vMtKilg/NIlCoSmdsGcGzntBlCtJWGcPMSPoz0lkin+dBmAnpSkI2Hyi7R+Y0aGTYq9AbnsPODyXCYI1Ob9OK1W0eJ2Zf5tknUoX7+DZN4vujiPshKclwr69i6fIXlIEvTyu2pQr8MU3kMlGZqNSxLeOs4Y8xGIgeJcKZPYfk1aHGP569xo45smYLW9lqvswBa5I3ySADhHGjwfD/DCnCu8WEYv7OYXkmYQzBBcMuCVnAA="


script:
  - make style codecov

after_success:
  - sonar-scanner -Dproject.settings=./.sonar-project.properties

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    # - stage: integration
    #   name: "Integration Tests"
    #   if: branch = main
    #   script:
    #     - make it
    - stage: tag
      name: "Tag For Release"
      if: branch = main && type = push
      before_script:
        - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
      script:
        - export OLD_VERSION=$(make version)
        - git config --global user.name "xmidt-bot"
        - git config --global user.email "$BOT_EMAIL"
        - export TAG=$(cat CHANGELOG.md | perl -0777 -ne 'print "$1" if /.*## \[Unreleased\]\s+## \[(v\d+.\d+.\d+)\].*/s')
        - export TODAY=`date +'%m/%d/%Y'`
        - export NOTES=$(cat CHANGELOG.md | perl -0777 -ne 'print "$ENV{TODAY}\n\n$1\n" if /.*## \[$ENV{TAG}\]\s(.*?)\s+## \[(v\d+.\d+.\d+)\].*/s')
        - if [[ "$TAG" != "" && "$TAG" != "$OLD_VERSION" ]]; then git tag -a "$TAG" -m "$NOTES"; git push origin --tags; echo $?; fi
      after_success: skip

    - stage: release
      name: "Make a Release"
      if: branch != main
      script: skip
      before_deploy:
        - make release-artifacts
      deploy:
        on:
          all_branches: true
          tags: true
        provider: releases
        api_key: "$GH_TOKEN"
        file_glob: true
        file: ./.ignore/*
        skip_cleanup: true
    - stage: docker-release
      name: "Make Docker Release"
      if: branch != main
      script: skip
      deploy:
        - provider: script
          script: bash deploy/docker_push
          on:
            all_branches: true
            tags: true
